# Aether local setup helper (Windows / PowerShell).
#
# What it does, in order:
#   1. Activates the venv at .venv (creates it if missing)
#   2. Installs the Python project in editable mode if pyserial is missing
#   3. Lists CH34x / CP210x USB-serial COM ports in Device Manager
#   4. Probes each one with scripts/probe_serial.py to find which is the RX
#      board (the one emitting CSI JSON)
#   5. Writes .env at the repo root with AETHER_SERIAL_PORT set to
#      that port
#   6. Prints next steps (start uvicorn + next dev)
#
# Re-runnable. If .env already exists with a working serial port, it leaves
# it alone unless -Force is passed. The probe is non-destructive: it opens
# the port for ~4 s, reads, closes.
#
# Usage:
#   .\scripts\setup_local.ps1
#   .\scripts\setup_local.ps1 -Force         # re-detect even if .env exists
#   .\scripts\setup_local.ps1 -Port COM5     # skip probe and pin a port

param(
  [switch]$Force,
  [string]$Port = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

Write-Host "[setup] repo root: $repoRoot"

# --- 1. venv ---
$venvActivate = Join-Path $repoRoot ".venv\Scripts\Activate.ps1"
if (-not (Test-Path $venvActivate)) {
  Write-Host "[setup] no venv found at .venv; creating one"
  python -m venv .venv
}
. $venvActivate

# --- 2. install pyserial via project deps if missing ---
$hasPyserial = $false
try {
  python -c "import serial" 2>$null
  $hasPyserial = $true
} catch {}
if (-not $hasPyserial) {
  Write-Host "[setup] pyserial missing; installing project (-e .[dev])"
  python -m pip install -e ".[dev]"
}

# --- 3. enumerate USB-serial ports ---
Write-Host ""
Write-Host "[setup] USB-serial ports on this PC:"
$serialPorts = Get-CimInstance Win32_PnPEntity |
  Where-Object { $_.Name -match "\(COM\d+\)" } |
  ForEach-Object {
    $name = $_.Name
    $com = if ($name -match "\((COM\d+)\)") { $matches[1] } else { $null }
    [pscustomobject]@{ Port = $com; Name = $name }
  } |
  Where-Object { $_.Port }
$serialPorts | Format-Table -AutoSize

if (-not $serialPorts -or $serialPorts.Count -eq 0) {
  Write-Host "[setup] RED: no COM ports found. Plug in the RX board (USB-C) and re-run."
  exit 1
}

# --- 4. probe to identify RX ---
$selectedPort = $Port
if (-not $selectedPort) {
  $envPath = Join-Path $repoRoot ".env"
  $existing = $null
  if ((Test-Path $envPath) -and (-not $Force)) {
    $existing = (Get-Content $envPath | Where-Object { $_ -match "^AETHER_SERIAL_PORT\s*=" } | Select-Object -First 1)
    if ($existing) {
      $existingPort = $existing.Split("=", 2)[1].Trim().Trim('"').Trim("'")
      if ($existingPort) {
        Write-Host "[setup] .env already pins AETHER_SERIAL_PORT=$existingPort (use -Force to re-detect)"
        $selectedPort = $existingPort
      }
    }
  }
  if (-not $selectedPort) {
    Write-Host ""
    Write-Host "[setup] probing each port for CSI traffic (4 s each)..."
    $probeArgs = @("scripts/probe_serial.py") + ($serialPorts | ForEach-Object { $_.Port })
    $probeOutput = & python @probeArgs
    $best = $null
    foreach ($line in $probeOutput) {
      try {
        $row = $line | ConvertFrom-Json
        $marker = if ($row.csi -gt 0) { "GREEN csi=$($row.csi) hb=$($row.heartbeat)" }
                  elseif ($row.heartbeat -gt 0) { "YELLOW heartbeat only" }
                  elseif (-not $row.opened) { "RED $($row.error)" }
                  else { "RED no JSON in 4 s" }
        Write-Host ("  {0,-6} -> {1}" -f $row.port, $marker)
        if ($row.csi -gt 0 -and (-not $best -or $row.csi -gt $best.csi)) {
          $best = $row
        }
      } catch {
        Write-Host "  (unparseable probe line: $line)"
      }
    }
    if (-not $best) {
      Write-Host ""
      Write-Host "[setup] RED: no port emitted CSI. Boards may not be flashed, or the RX is held by another program."
      Write-Host "        - Close PuTTY / Arduino IDE Serial Monitor on those ports."
      Write-Host "        - Re-run scripts/flash_rx.ps1 if firmware is missing."
      exit 1
    }
    $selectedPort = $best.port
    Write-Host "[setup] selected RX port: $selectedPort"
  }
}

# --- 5. write .env ---
$envPath = Join-Path $repoRoot ".env"
$envExists = Test-Path $envPath
if ($envExists -and -not $Force) {
  # Update only the SERIAL_PORT line, preserve everything else.
  $lines = Get-Content $envPath
  $found = $false
  $newLines = $lines | ForEach-Object {
    if ($_ -match "^AETHER_SERIAL_PORT\s*=") {
      $found = $true
      "AETHER_SERIAL_PORT=$selectedPort"
    } else { $_ }
  }
  if (-not $found) {
    $newLines += "AETHER_SERIAL_PORT=$selectedPort"
  }
  Set-Content -Path $envPath -Value $newLines -Encoding UTF8
  Write-Host "[setup] updated .env -> AETHER_SERIAL_PORT=$selectedPort"
} else {
  $template = @"
# Aether local environment - generated by scripts/setup_local.ps1
AETHER_API_HOST=127.0.0.1
AETHER_API_PORT=8000
AETHER_LOG_LEVEL=INFO
AETHER_SERIAL_PORT=$selectedPort
AETHER_BAUD=115200
AETHER_REPLAY_PATH=
AETHER_DATA_DIR=./data
AETHER_SESSION_DB=./data/aether.sqlite
AETHER_KB_ROOT=./docs
NEXT_PUBLIC_AETHER_API=http://127.0.0.1:8000
NEXT_PUBLIC_AETHER_WS=ws://127.0.0.1:8000/ws/live
"@
  Set-Content -Path $envPath -Value $template -Encoding UTF8
  Write-Host "[setup] wrote new .env with AETHER_SERIAL_PORT=$selectedPort"
}

Write-Host ""
Write-Host "[setup] DONE. Next steps:"
Write-Host "  1. Stop any running uvicorn (Ctrl-C in its terminal)."
Write-Host "  2. python -m uvicorn apps.api.src.main:app --reload --host 127.0.0.1 --port 8000"
Write-Host "     -> the boot line should show 'serial_port=$selectedPort'"
Write-Host "  3. In another terminal: npm run web:dev"
Write-Host "  4. Open http://localhost:3000  -> Live Room  -> click Start session."
Write-Host "  5. Hold the room empty -> Calibrate (10 s)."
